# Generated by Django 2.1.3 on 2018-12-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181228_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumb',
            field=models.ImageField(blank=True, default='null.png', upload_to=''),
        ),
    ]
